
default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: db
  port: 5432
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  host: <%= ENV["DATABASE_HOST"] %>
  database: udemy_clone_test

production:
  primary: &primary_production
    <<: *default
    database: udemy_clone_production
    username: udemy_clone
    password: <%= ENV["UDEMY_CLONE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: udemy_clone_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: udemy_clone_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: udemy_clone_production_cable
    migrations_paths: db/cable_migrate
